name: release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Release and Upload Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set git tag output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Patch manifest (add tag)
        run: |
          TAG="${{ steps.vars.outputs.tag }}"
          VERSION=${TAG#v}
          jq --arg ver "$VERSION" '.version = $ver' src/manifest.json > temp.json && mv temp.json src/manifest.json

      - name: Build project (ZIP)
        run: |
          cd src
          zip -r ../ambassador-referral-linker.zip .

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ambassador-referral-linker.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
